prison:
  world: Jail
  x: -32.0
  y: 28.0
  z: -74.0
  yaw: 0.0
  pitch: 0.0
  duration-minutes: 2880

head:
  drop-chance-percent: 100.0
  effect: POISON
  duration-seconds: 30
  amplifier: 0

death:
  sound: ENTITY_WITHER_SPAWN
  sound-volume: 1.0
  sound-pitch: 1.0

new-player-protection:
  duration-minutes: 30
  resistance-amplifier: 4

duel:
  world: duel
  return-delay-seconds: 30
  request-expiry-seconds: 60
  zone-count: 3
  item-cleanup-radius-blocks: 100.0
  zones:
    1:
      a: {x: 0.0, y: 100.0, z: 0.0, yaw: 0.0, pitch: 0.0}
      b: {x: 10.0, y: 100.0, z: 0.0, yaw: 180.0, pitch: 0.0}
    2:
      a: {x: 0.0, y: 100.0, z: 50.0, yaw: 0.0, pitch: 0.0}
      b: {x: 10.0, y: 100.0, z: 50.0, yaw: 180.0, pitch: 0.0}
    3:
      a: {x: 0.0, y: 100.0, z: 100.0, yaw: 0.0, pitch: 0.0}
      b: {x: 10.0, y: 100.0, z: 100.0, yaw: 180.0, pitch: 0.0}

combat:
  disconnect-grace-seconds: 300
  tag-seconds: 20

alexbanniere:
  enabled: true
  target-player: AlexJanOne
