name: DeathBan
version: '${version}'
main: thomjap.deathban.DeathBan
api-version: '1.21'
author: Toi
description: Exclure un joueur pour une durée définie après sa mort.
commands:
  db:
    description: Commandes DeathBan
    usage: /db <unprison|set|reload>